/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package attheraces;

import java.io.File;
import util.jfilechooser.SelecionarArquivosDiretorios;

/**
 *
 * @author marce
 */
public class FormConfiguraExcel extends javax.swing.JDialog {

    private File diretorio;
    public int BTN_PRESSIONADO = 0;
    public int BTN_OK = 1;
    public int BTN_CANCELAR = 2;
    
    /**
     * Creates new form FormConfiguraExcel
     */
    public FormConfiguraExcel(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        diretorio = new File(Attheraces.DIR_PADRAO + "Attheraces.xls");
        txtDiretorio.setText(diretorio.getAbsolutePath());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        rbCriarArquivoParaCadaMes = new javax.swing.JRadioButton();
        rbCriarArquivoParaCadaMeSepararAbas = new javax.swing.JRadioButton();
        rbCriarUnicoArquivo = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txtDiretorio = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configurar Exportação");

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jButton1.setText("Exportar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Arquivo:"));

        buttonGroup1.add(rbCriarArquivoParaCadaMes);
        rbCriarArquivoParaCadaMes.setText("Criar um arquivo para cada mês");
        rbCriarArquivoParaCadaMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCriarArquivoParaCadaMesActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbCriarArquivoParaCadaMeSepararAbas);
        rbCriarArquivoParaCadaMeSepararAbas.setText("Criar um arquivo para cada mês e separar os dias em abas");
        rbCriarArquivoParaCadaMeSepararAbas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCriarArquivoParaCadaMeSepararAbasActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbCriarUnicoArquivo);
        rbCriarUnicoArquivo.setSelected(true);
        rbCriarUnicoArquivo.setText("Criar um único arquivo do excel");
        rbCriarUnicoArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCriarUnicoArquivoActionPerformed(evt);
            }
        });

        jLabel1.setText("Diretório:");

        txtDiretorio.setEditable(false);

        jButton3.setText("Selecionar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rbCriarUnicoArquivo)
                        .addGap(18, 18, 18)
                        .addComponent(rbCriarArquivoParaCadaMes)
                        .addGap(18, 18, 18)
                        .addComponent(rbCriarArquivoParaCadaMeSepararAbas))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDiretorio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbCriarUnicoArquivo)
                    .addComponent(rbCriarArquivoParaCadaMes)
                    .addComponent(rbCriarArquivoParaCadaMeSepararAbas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDiretorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        BTN_PRESSIONADO = BTN_OK;
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(rbCriarUnicoArquivo.isSelected()) {
            diretorio = new SelecionarArquivosDiretorios().localizarArquivo();
            if(diretorio != null) {
                if(!diretorio.getAbsolutePath().toLowerCase().endsWith(".xls")) {
                    diretorio = new File(diretorio.getAbsolutePath() + ".xls");
                }
            }
        }
        if(rbCriarArquivoParaCadaMes.isSelected() || rbCriarArquivoParaCadaMeSepararAbas.isSelected()) {
            diretorio = new SelecionarArquivosDiretorios().localizarDiretorio();
            if(diretorio != null) {
                if(!diretorio.getAbsolutePath().toLowerCase().endsWith("\\")) {
                    diretorio = new File(diretorio.getAbsolutePath() + "\\");
                }
            }
        }
        if(diretorio != null) {
            txtDiretorio.setText(diretorio.getAbsolutePath());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void rbCriarArquivoParaCadaMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCriarArquivoParaCadaMesActionPerformed
        diretorio = new File(Attheraces.DIR_PADRAO);
        txtDiretorio.setText(diretorio.getAbsolutePath());
    }//GEN-LAST:event_rbCriarArquivoParaCadaMesActionPerformed

    private void rbCriarArquivoParaCadaMeSepararAbasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCriarArquivoParaCadaMeSepararAbasActionPerformed
        diretorio = new File(Attheraces.DIR_PADRAO);
        txtDiretorio.setText(diretorio.getAbsolutePath());
    }//GEN-LAST:event_rbCriarArquivoParaCadaMeSepararAbasActionPerformed

    private void rbCriarUnicoArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCriarUnicoArquivoActionPerformed
        diretorio = new File(Attheraces.DIR_PADRAO + "Attheraces.xls");
        txtDiretorio.setText(diretorio.getAbsolutePath());
    }//GEN-LAST:event_rbCriarUnicoArquivoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    public boolean isCriarUnicoArquivo() {
        return rbCriarUnicoArquivo.isSelected();
    }
    
    public boolean isCriarArquivoParaCadaMes() {
        return rbCriarArquivoParaCadaMes.isSelected();
    }
    
    public boolean isCriarArquivoParaCadaMesSepararAbas() {
        return rbCriarArquivoParaCadaMeSepararAbas.isSelected();
    }
    
    public File getDiretorio() {
        return diretorio;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton rbCriarArquivoParaCadaMeSepararAbas;
    private javax.swing.JRadioButton rbCriarArquivoParaCadaMes;
    private javax.swing.JRadioButton rbCriarUnicoArquivo;
    private javax.swing.JTextField txtDiretorio;
    // End of variables declaration//GEN-END:variables
}
